--TEST:  Check for duplicate User accounts.
SELECT ID, COUNT(1)
FROM USERS 
GROUP BY ID
HAVING COUNT(1) > 1
--RESULT:  70 User records with duplicated User IDs

--TEST:  Check for NULLs in important User fields.
SELECT SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) null_ids
, SUM(CASE WHEN ACTIVE IS NULL THEN 1 ELSE 0 END) null_active
, SUM(CASE WHEN CREATEDDATE IS NULL THEN 1 ELSE 0 END) null_createdate
, SUM(CASE WHEN ROLE IS NULL THEN 1 ELSE 0 END) null_role
, SUM(CASE WHEN SIGNUPSOURCE IS NULL THEN 1 ELSE 0 END) null_signupsource
, SUM(CASE WHEN STATE IS NULL THEN 1 ELSE 0 END) null_state
FROM USERS 
--RESULT:  48 NULL values in SignUpSource.  56 NULL values in State fields.

--TEST:  Check for orphaned User Ids in receipts data: user IDs that are not in Users data
SELECT COUNT(distinct RECEIPTS.USERID) missing_user_IDs
FROM RECEIPTS
LEFT JOIN USERS ON RECEIPTS.USERID = USERS.ID
WHERE USERS.ID IS NULL
--RESULT:  117 orphaned IDs

--TEST:  Find NULLs in important Receipts fields
SELECT SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) null_receipt_ids
, SUM(CASE WHEN CREATEDATE IS NULL THEN 1 ELSE 0 END) null_createdate
, SUM(CASE WHEN DATESCANNED IS NULL THEN 1 ELSE 0 END) null_datescanned
, SUM(CASE WHEN PURCHASEDITEMCOUNT IS NULL AND REWARDSRECEIPTSTATUS IN ('FINISHED','REJECTED') THEN 1 ELSE 0 END) null_purchaseditemcount
, SUM(CASE WHEN REWARDSRECEIPTSTATUS IS NULL THEN 1 ELSE 0 END) null_recwardsreceiptstatus
, SUM(CASE WHEN REWARDSRECEIPTSTATUS IS NULL THEN 1 ELSE 0 END) null_totalspent
FROM RECEIPTS 
--RESULT: No issues

--TEST:  Find barcodes in rewardsReceiptItemList data that are missing from Brands data
SELECT COUNT(DISTINCT RRI.BARCODE)
FROM REWARDSRECEIPTITEM RRI
LEFT JOIN BRANDS ON RRI.BARCODE = BRANDS.BARCODE
WHERE BRANDS.BARCODE IS NULL
--RESULT:  552 barcodes missing from Brands table.


--TEST:  Find brandcodes in rewardsReceiptItem data that are missing from Brands data
SELECT COUNT(DISTINCT RRI.BRANDCODE)
FROM REWARDSRECEIPTITEM RRI
LEFT JOIN BRANDS ON RRI.BRANDCODE = BRANDS.BRANDCODE
WHERE BRANDS.BRANDCODE IS NULL
--RESULT:  186 brand codes missing from Brands table.

--TEST:  Reconcile pointsEarned in rewardsReceiptItemsList with pointsEarned in Receipts table 
-- for records with RewardsReceiptStatus of Finished.
SELECT RECEIPTS.ID, RewardsReceiptStatus
, RECEIPTS.POINTSEARNED
, SUM(CASE WHEN RRI.POINTSEARNED IS NULL THEN 0 ELSE RRI.POINTSEARNED END ) REWARDSRECEIPTITEM_POINTSEARNED
FROM RECEIPTS
LEFT JOIN REWARDSRECEIPTITEM RRI
ON RECEIPTS.ID = RRI.RECEIPTID
WHERE RECEIPTS.REWARDSRECEIPTSTATUS IN ('FINISHED')
GROUP BY RECEIPTS.ID, RewardsReceiptStatus
HAVING RECEIPTS.POINTSEARNED != SUM(CASE WHEN RRI.POINTSEARNED IS NULL THEN 0 ELSE RRI.POINTSEARNED END )
--RESULT:  460 receipts with POINTSEARNED values that do not reconcile.